version: "3.8"

services:

  autoheal:
    image: willfarrell/autoheal
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AUTOHEAL_CONTAINER_LABEL: "autoheal"
      AUTOHEAL_START_PERIOD: 30
      AUTOHEAL_INTERVAL: 10
      AUTOHEAL_DEFAULT_STOP_TIMEOUT: 10
      CURL_TIMEOUT: 5
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    command: postgres -c ssl=off
    environment:
      POSTGRES_DB: honeydukes_db
      POSTGRES_USER: hdshop_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - hdshop-db-data-15:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U hdshop_user -d honeydukes_db
      interval: 10s
      timeout: 5s
      retries: 6

  backend:
    image: hdshop-backend
    restart: unless-stopped
    ports:
      - 3001:3001
    command: sh -c "npm run migration-up && npm start"
    environment:
      DB_USERNAME: hdshop_user
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: honeydukes_db
      DB_HOST: db
      DB_PORT: 5432
      DB_DIALECT: postgres
      PORT: 3001
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl 'http://127.0.0.1:3001/ping'
      interval: 10s
      timeout: 5s
      retries: 6
  
volumes:
  hdshop-db-data-15:
